// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbyfrwfBQV0D1zjVxJyQoM7pmLxIhzltc',
    appId: '1:271053604729:web:0f0821cca7d55bf4b351a8',
    messagingSenderId: '271053604729',
    projectId: 'reciclapp-77df6',
    authDomain: 'reciclapp-77df6.firebaseapp.com',
    storageBucket: 'reciclapp-77df6.firebasestorage.app',
    measurementId: 'G-89T19M7B5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7IXGkvYNw7JH8J6FevDQI_h-AKeSkKyo',
    appId: '1:271053604729:android:28c7aa49ac072428b351a8',
    messagingSenderId: '271053604729',
    projectId: 'reciclapp-77df6',
    storageBucket: 'reciclapp-77df6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWPHygXZ5VcBnJYBh_LsVlNL2mhszyam8',
    appId: '1:271053604729:ios:24db0d1235228c38b351a8',
    messagingSenderId: '271053604729',
    projectId: 'reciclapp-77df6',
    storageBucket: 'reciclapp-77df6.firebasestorage.app',
    iosBundleId: 'com.example.reciclapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWPHygXZ5VcBnJYBh_LsVlNL2mhszyam8',
    appId: '1:271053604729:ios:24db0d1235228c38b351a8',
    messagingSenderId: '271053604729',
    projectId: 'reciclapp-77df6',
    storageBucket: 'reciclapp-77df6.firebasestorage.app',
    iosBundleId: 'com.example.reciclapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbyfrwfBQV0D1zjVxJyQoM7pmLxIhzltc',
    appId: '1:271053604729:web:886e7bf33d3af535b351a8',
    messagingSenderId: '271053604729',
    projectId: 'reciclapp-77df6',
    authDomain: 'reciclapp-77df6.firebaseapp.com',
    storageBucket: 'reciclapp-77df6.firebasestorage.app',
    measurementId: 'G-GD2M0NQJV9',
  );
}
